### ISSUE TITLE
Can't start an observer client with a PTZ camera to play around

### ISSUE THREAD

**Issue by isaryo** [JunweiLiang/Multiverse#18]
I tried to [it](https://github.com/JunweiLiang/Multiverse/tree/master/forking_paths_dataset#step-1-prepare-and-test-the-carla-simulator).

Then I received the following error message.

```
Traceback (most recent call last):
  File "code/spectator.py", line 21, in <module>
    from utils import anchor_cameras
  File "/home/use/Multiverse/forking_paths_dataset/code/utils.py", line 77, in <module>
    sun_azimuth_angle=20.0)
Boost.Python.ArgumentError: Python argument types in
    WeatherParameters.__init__(WeatherParameters)
did not match C++ signature:
    __init__(_object*, float cloudiness=0.0, float precipitation=0.0, float precipitation_deposits=0.0, float wind_intensity=0.0, float sun_azimuth_angle=0.0, float sun_altitude_angle=0.0, float fog_density=0.0, float fog_distance=0.0, float fog_falloff=0.0, float wetness=0.0)
    __init__(_object*)
```
Do you have any solutions?

**Comment by JunweiLiang** [comment]
This may be because you have installed a different carla python environment. Try uninstalling carla and run again. This [line](https://github.com/JunweiLiang/Multiverse/blob/master/forking_paths_dataset/code/spectator.py#L16) in spectator.py imports the carla 0.9.6 library from the *.egg file in the repo.
