### ISSUE TITLE
"Person" class in semantic segmentation input

### ISSUE THREAD

**Issue by TheDarkKnight1998** [JunweiLiang/Multiverse#23]
Why do the ten categories of semantic segmentation results not include pedestrians? Do they serve as background?

**Comment by JunweiLiang** [comment]
Originally in the next-prediction repo, we use ADE20K model and only these most common [10 classes](https://next.cs.cmu.edu/data/072019_prepare_data/scene36_64_id2name_top10.json) are used in preprocessing, which does not include "person" class since person features are covered in another module. See [here](https://github.com/JunweiLiang/next-prediction/blob/master/code/prepare_data/README.md#step-3-get-scene-semantic-segmentation-features-ade20k-pre-trained-model). Since in the ActEV dataset these are the most common classes except for person class and to keep the same preprocessing, I put the person class into the background (id 0). This is a bit hacky. You can easily change this by adding an entry in the `scene36_64_id2name_top10.json` file ("13" is person class for ADE20K) for training and testing but may not see a performance difference.

**Comment by TheDarkKnight1998** [comment]
Thank you for your explanation！
